# Company Information
company_name: ADASSA Enterprises
domain_name: adassa.com.jm
address_line: 'Kingston, Jamaica'
telephone_number: 876-289-1644
company_email: mail@adassa.com.jm
description: 'This is the ADASSA group of companies website.'
meta_description: 'business management system, engineering, 
                   information technology'
                   
aboutPage: true

email: mail@adassa.com.jm
author: 'Desmond Bennett'
authorTwitter:  https://twitter.com/dpbennett
baseurl: /
url: https://adassa.com.jm

# Social Link
facebook_link: https://www.facebook.com/desmondpbennett
twitter_link: https://twitter.com/DPB_and_A
github_link: https://github.com/Adassa-Enterprises

disqus: false
disqus_shortname: adassa

paginate: 20

# Build settings
markdown: kramdown