# Company Information
company_name: Adassa Store
domain_name: store.adassa.com.jm
address_line: Kingston
country: Jamaica
company_email: mail@adassa.com.jm
description: This is the Adassa Store website.
meta_description: business management system, engineering, 
                   information technology
  
# Site Information
title: Adassa Store
author: Desmond Bennett
authorTwitter:  https://twitter.com/dpbennett
baseurl: /
url: https://adassa.com.jm

# Social Link
facebook_link: https://www.facebook.com/desmondpbennett
twitter_link: https://twitter.com/DPB_and_A
github_link: https://github.com/Adassa-Enterprises

disqus: false
disqus_shortname: adassa

paginate: 20

# Build settings
markdown: kramdown